name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: INIT
        run: go mod init


      - name: Get dependencies
        run: go mod download

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o hash-banger-linux

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o hash-banger-windows.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o hash-banger-macos

      - name: Create Release (Draft)
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' # Only create a draft release on pushes to main
        with:
          files: |
            hash-banger-linux
            hash-banger-windows.exe
            hash-banger-macos
          name: Latest Build (Draft)
          draft: true
          prerelease: true  # Mark as a pre-release


      - name: Create Release (Tagged)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') # Only create a full release on tags starting with 'v'
        with:
          files: |
            hash-banger-linux
            hash-banger-windows.exe
            hash-banger-macos
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}

      - name: Upload artifacts (main branch)
        uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/main' # Only upload artifacts on pushes to main
        with:
          name: hash-banger-latest
          path: |
            hash-banger-linux
            hash-banger-windows.exe
            hash-banger-macos
