name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Get dependencies
        run: go mod download

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o hash-banger-linux

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o hash-banger-windows.exe

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o hash-banger-macos

      - name: Upload artifacts (main branch)
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: hash-banger-latest
          path: |
            hash-banger-linux
            hash-banger-windows.exe
            hash-banger-macos

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: |
            hash-banger-linux
            hash-banger-windows.exe
            hash-banger-macos
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "Release ${{ github.ref }} of hash-banger.  Includes binaries for Linux, macOS, and Windows." #  Add release notes or other information here.
